package com.sylvain.chess.play;

public enum GameStatus {
  CHECKMATE,
  RESIGNED,
  STALEMATE,
  UNIMPROVING_MOVES,
  SEVERAL_TIMES_SAME_POSITION,
  ALMOST_EMPTY_BOARD,
  PLAYING,
  ABORTED_MAX_NB_OF_MOVES
}